[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit BMP085 Library
